Add message broker module
materials-marketplace/python-sdk pull request #11
Opened 2022-05-16 17:50 UTC by yoavnash

2022-05-19 16:07 UTC, csadorf reviewed
Just a few suggestions. I think this is generally good enough for a starting point.

2022-05-19 16:07 UTC, csadorf commented on MANIFEST.in
> +include examples/rpc_server.py
Actually, I don't think there is any good reason to include the examples with the wheel. The whole directory should be recursively excluded.

2022-05-19 16:07 UTC, csadorf commented on examples/rpc_server.py
> +application_id = "3a9e9445-5d59-4d74-a26a-a4cfff366a01"
Do we really have to include a specific application id with the example?

2022-05-19 16:07 UTC, csadorf commented on marketplace/message_broker/rpc_server.py
> +        )  # Delete old queue. Otherwise, first message might not be consumed.
This is not concurrency-safe, is it?

2022-05-19 16:07 UTC, csadorf commented on marketplace/message_broker/rpc_server.py
> +            message.body = body_dict
```suggestion
            message.body = json.loads(body_str) if body_str else None
```

2022-05-23 08:01 UTC, yoavnash commented on MANIFEST.in
> +include examples/rpc_server.py
Fixed via a new commit.

2022-05-23 08:01 UTC, yoavnash commented on examples/rpc_server.py
> +application_id = "3a9e9445-5d59-4d74-a26a-a4cfff366a01"
Fixed via a new commit.

2022-05-23 08:02 UTC, yoavnash commented on marketplace/message_broker/rpc_server.py
> +            message.body = body_dict
Fixed via a new commit.

2022-05-23 08:04 UTC, yoavnash commented on marketplace/message_broker/rpc_server.py
> +        )  # Delete old queue. Otherwise, first message might not be consumed.
I'm not sure, but indeed this was a quick a dirty solution to the problem described in the comment.

2022-05-23 08:12 UTC, csadorf commented on marketplace/message_broker/rpc_server.py
> +        )  # Delete old queue. Otherwise, first message might not be consumed.
Can you clarify what problem this is working-around? I am not exactly sure what you mean by "first message might not be consumed".

2022-05-23 09:23 UTC, yoavnash commented on marketplace/message_broker/rpc_server.py
> +        )  # Delete old queue. Otherwise, first message might not be consumed.
I haven't gotten to the bottom of it so far.

2022-05-27 18:57 UTC, yoavnash commented
New changes:
- Model for response was added
- Renaming of queue name from <application-id> to <application-id>:<hash(application-id,application-secret)> (to increase security)

@pablo-de-andres for info.

2022-05-30 10:17 UTC, csadorf requested changes
As discussed offline, please move the models into the https://github.com/materials-marketplace/standard-app-api code base. PR should be into the [version-0.1.0 branch](https://github.com/materials-marketplace/standard-app-api/tree/version-0.1.0) until that is merged.

I would suggest that you address my other comments prior to the move so that we can conclude the discussion before clustering it across repositories.

2022-05-30 10:17 UTC, csadorf commented on marketplace/message_broker/models/request_message.py
> +    body: Optional[Any] = Field(None, description="The request message payload")
Is `Any` really the correct type here? This should be a message string or binary stream, no? In which case `str` or `bytes` would be more appropriate.

2022-05-30 10:17 UTC, csadorf commented on marketplace/message_broker/models/request_message.py
> +    headers: Optional[Dict[str, str]] = Field(None, description="Request headers")
Can headers not be further nested?

2022-05-30 10:17 UTC, csadorf commented on marketplace/message_broker/models/response_message.py
> +    body: Optional[Any] = Field(None, description="The response message payload")
Same question as above.

2022-05-30 10:17 UTC, csadorf commented on marketplace/message_broker/models/response_message.py
> +    headers: Optional[Dict[str, str]] = Field(None, description="Response headers")
Same question as above.

2022-05-30 10:17 UTC, csadorf commented on marketplace/message_broker/models/request_message.py
> +class RequestMessage(BaseModel):
```suggestion
class MessageBrokerRequestModel(BaseModel):
```

2022-05-30 10:17 UTC, csadorf commented on marketplace/message_broker/models/response_message.py
> +class ResponseMessage(BaseModel):
```suggestion
class MessageBrokerResponseModel(BaseModel):
```

2022-05-30 10:17 UTC, csadorf commented on marketplace/message_broker/models/request_message.py
> +from typing import Any, Dict, Optional
I think we can probably put all message broker-related models into one `message_broker/models.py` module.

2022-05-30 10:17 UTC, csadorf commented on marketplace/message_broker/models/request_message.py
> +    body: Optional[Any] = Field(None, description="The request message payload")
Why do we need two different body fields (`body_base64` and `body`)?

2022-05-30 10:17 UTC, csadorf commented on marketplace/message_broker/rpc_server.py
> +        self.endpoint_callback = endpoint_callback
Would the name `callback_endpoint` make more sense?

2022-05-30 10:17 UTC, csadorf commented on marketplace/message_broker/rpc_server.py
> +        )  # Delete old queue. Otherwise, first message might not be consumed.
Can we make it more obvious in the comment that this is a work-around that may be related to some not yet understood issue?

2022-05-30 12:53 UTC, yoavnash commented on marketplace/message_broker/models/request_message.py
> +    body: Optional[Any] = Field(None, description="The request message payload")
In can also by JSON. For example: https://github.com/materials-marketplace/python-sdk/blob/message_broker/examples/rpc_server.py#L11
Therefore I think `Any` is more generic.

2022-05-30 12:54 UTC, yoavnash commented on marketplace/message_broker/models/request_message.py
> +    headers: Optional[Dict[str, str]] = Field(None, description="Request headers")
What do you by further nested?

2022-05-30 13:26 UTC, yoavnash commented on marketplace/message_broker/models/response_message.py
> +class ResponseMessage(BaseModel):
Renamed in https://github.com/materials-marketplace/standard-app-api/pull/5

2022-05-30 13:27 UTC, yoavnash commented on marketplace/message_broker/models/request_message.py
> +from typing import Any, Dict, Optional
Done in https://github.com/materials-marketplace/standard-app-api/pull/5

2022-05-30 13:32 UTC, yoavnash commented on marketplace/message_broker/models/request_message.py
> +    body: Optional[Any] = Field(None, description="The request message payload")
I agree. I think `body` can be removed. Will do so after https://github.com/materials-marketplace/standard-app-api/pull/5 is approved.

2022-05-30 13:38 UTC, yoavnash commented on marketplace/message_broker/models/request_message.py
> +    body: Optional[Any] = Field(None, description="The request message payload")
As mentioned below, the `body` could actually be removed completely.

2022-05-30 15:20 UTC, csadorf commented on marketplace/message_broker/models/request_message.py
> +    headers: Optional[Dict[str, str]] = Field(None, description="Request headers")
I meant having a dictionary as value, but that's not the case ,so we can close this.

2022-05-30 16:49 UTC, csadorf commented on marketplace/message_broker/rpc_server.py
> +        self.endpoint_callback = endpoint_callback
What is the exact purpose of this callback?

2022-05-31 07:44 UTC, yoavnash commented on marketplace/message_broker/rpc_server.py
> +        self.endpoint_callback = endpoint_callback
This callback function is being called to process an incoming message. Example: https://github.com/materials-marketplace/python-sdk/blob/message_broker/examples/rpc_server.py#L9

2022-05-31 10:23 UTC, yoavnash commented on marketplace/message_broker/rpc_server.py
> +        self.endpoint_callback = endpoint_callback
Sure, I think `message_handler` would be the most descriptive one.

2022-05-31 14:22 UTC, yoavnash commented on marketplace/message_broker/rpc_server.py
> +        )  # Delete old queue. Otherwise, first message might not be consumed.
I removed it completely since I was not able to reproduce it.

2022-05-31 14:22 UTC, yoavnash commented on marketplace/message_broker/rpc_server.py
> +        )  # Delete old queue. Otherwise, first message might not be consumed.
I removed it since I was not able to reproduce it.

2022-05-31 15:32 UTC, yoavnash commented
> @yoavnash How do you want to move forward? Should we make a (pre-?) release of https://github.com/materials-marketplace/standard-app-api and then update the PR here? Or do you want to temporarily depend on the git repository?

I think it would be great to have a proper release of the `standard-app-api` package, as well as to publish it in PyPI. Then we can update this PR so that the models are imported from that repo.

2022-06-01 11:23 UTC, csadorf commented
Blocked by: https://github.com/materials-marketplace/standard-app-api/issues/10

2022-06-01 14:12 UTC, yoavnash commented
Great :)

2022-06-01 14:27 UTC, yoavnash commented
Some tests fail. @csadorf Do you think it has to do with the api package not supporting Python 3.8?

2022-06-02 07:48 UTC, yoavnash commented
Done. It's still failing though

2022-06-02 08:13 UTC, csadorf commented
> Done. It's still failing though

Yes, I think this is an unrelated issue either with the runners or the actions. Currently checking whether updating the actions in #16 resolves the issue.

2022-06-02 08:18 UTC, csadorf commented
@yoavnash #16 has passed, would you mind rebasing once more on `main`? Also, I am not sure whether your previous rebase was clean since there are some changes that should not be there, e.g., https://github.com/materials-marketplace/python-sdk/pull/11/files#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03f .

2022-06-02 09:38 UTC, yoavnash commented
This time I merged instead of rebasing. The problem seems to be resolved. Thanks.
I think we can now proceed with merging this branch into main.

2022-06-02 09:46 UTC, csadorf requested changes
I think the dependencies must be adjusted, otherwise good.

2022-06-02 09:46 UTC, csadorf commented on setup.cfg
> +    pydantic==1.9.0
Pydantic is not a direct dependency, is it?

2022-06-02 10:27 UTC, yoavnash commented on setup.cfg
> +    pydantic==1.9.0
Indeed. Removed.

2022-06-02 11:03 UTC, csadorf approved these changes

2022-06-02 11:03 UTC, merged

2022-06-02 11:03 UTC, csadorf commented
Thanks a lot @yoavnash ! 👍