Move HPC-gateway related SDK method to this repo
materials-marketplace/python-sdk pull request #18
Opened 2022-06-29 12:24 UTC by unkcpz

The HPC-gateway app uses the available capabilities but with some modifications on the request and response format. The HPC-SDK https://github.com/unkcpz/hpc-sdk is designed to handle those requests over python. 
It will be a good idea to only have `python-sdk` to maintain everything.

2022-06-29 14:56 UTC, csadorf commented on marketplace/app/utils.py
> +    def decorator_check(func):
You can implement an "optional" argument for a decorator like this:
```python
from functools import wraps, partial

def check(func, name=None):

    if callable(func):

        @wraps(func)
        def inner(*args, **kwargs):
            print(f"Running '{name or func.__name__}'.")
            func(*args, **kwargs)

        return inner

    elif isinstance(func, str):
        return partial(check, name=func)


@check
def foo():
    print("I am foo.")


@check("baz")
def bar():
    print("I am bar.")


foo()
bar()
```

2022-06-30 12:00 UTC, unkcpz commented on marketplace/app/hpc_app.py
> +        return self.get(path="heartbeat").text
This is a duplicate of `MarkepPlaceApp`. Any suggestion on how to organize them? @csadorf

2022-06-30 12:33 UTC, csadorf requested changes
I assume that the function is fine, but this appears more like a draft to me. I'd appreciate if you could improve the code and documentation quality.

2022-06-30 12:33 UTC, csadorf commented on .gitignore
> +.env
What is the motivation for this?

2022-06-30 12:33 UTC, csadorf commented on marketplace/app/hpc_app.py
> +        return self.get(path="heartbeat").text
I'd suggest to make [`MarketPlaceApp`](https://github.com/materials-marketplace/python-sdk/blob/4e917e3f520647d26fead22aad2224bc2e79acf9/marketplace/app/marketplace_app.py#L16) inherit from this class and to remove this function.

2022-06-30 12:33 UTC, csadorf commented on marketplace/app/hpc_app.py
> +    def list_job(self):
```suggestion
    def list_jobs(self):
```

2022-06-30 12:33 UTC, csadorf commented on marketplace/app/hpc_app.py
> +        """upload file to remote path `resourceid` from source path"""
Can you make sure to use consistent capitalization and formatting for your doc-strings?

2022-06-30 12:33 UTC, csadorf commented on marketplace/app/hpc_app.py
> +        Return the folder name for further opreration."""
This seems like an implementation detail to me.

2022-06-30 12:33 UTC, csadorf commented on marketplace/app/hpc_app.py
> +        TODO, check the job script ready"""
Can you remove all of these comments that appear developer-targeted?

2022-06-30 12:33 UTC, csadorf commented on marketplace/app/hpc_app.py
> +        It actually drop entity from DB.
All of the "actually" comments should be removed.

2022-06-30 12:33 UTC, csadorf commented on marketplace/app/utils.py
> +                print("list cap: ", instance.capabilities)
left-over from debugging?

2022-06-30 12:33 UTC, csadorf commented on marketplace/app/utils.py
> +def check_capability_availability(func_or_str, capability=None):
```suggestion
def check_capability_availability(func_or_capability, capability=None):
```

2022-06-30 12:33 UTC, csadorf commented on marketplace/app/hpc_app.py
> +        return resp.text
Why is this returning anything?

2022-06-30 12:56 UTC, unkcpz reviewed
@csadorf thanks! Updated upon your suggestion. And I have test with running it with HPC app.

2022-06-30 12:56 UTC, unkcpz commented on .gitignore
> +.env
I add an example `hpc_api.ipynb` which will read access_token from `.env`.

2022-07-04 08:45 UTC, csadorf approved these changes
There are still a lot of issues with the doc-string formatting, however since this is not isolated to this change set, I think it is ok to merge and then work on improving that in a separate PR (#19).

2022-07-04 08:46 UTC, csadorf commented
@pablo-de-andres Do you still want to review this or ok to merge?

2022-07-04 08:57 UTC, pablo-de-andres commented
You can go ahead for me. I think I would maybe try to unify/simplify the behaviour of the decorator (to only check the function name, or to always require the capability), but it does not need to be done here.

2022-07-04 08:58 UTC, merged