update documentation per latest version
materials-marketplace/python-sdk pull request #34
Opened 2022-08-23 10:21 UTC by singhpranjali

Issues addressed: https://github.com/materials-marketplace/python-sdk/issues/33 and https://github.com/materials-marketplace/python-sdk/issues/30

2022-08-23 10:36 UTC, singhpranjali reviewed
In the previous sdk_version, we provide user the ability to pass additional arguments as parameters, like in [start_transformation](https://github.com/materials-marketplace/python-sdk/blob/main/marketplace/app/v0_0_1/transformation_app.py#L40). But in the new version, this is currently not possible [(here)](https://github.com/materials-marketplace/python-sdk/blob/main/marketplace/app/v0/transformation.py#L63). Should we be supporting additional arguments in the new version?

@csadorf @pablo-de-andres Please let me know your thoughts

2022-08-23 10:36 UTC, singhpranjali commented on examples/mp_api.py
> +my_mp_app = MyMarketPlaceApp(app_id="<application_client_id>", client=mp_client)
Using the above approach In the new version, we are expecting the user to first instantiate MarketPlaceClient and use it to instantiate their MarketPlaceApp. I believe we should also allow users to provide access_token and optionally host_url directly without having to first instantiate the client.

2022-08-23 13:03 UTC, csadorf commented
> In the previous sdk_version, we provide user the ability to pass additional arguments as parameters, like in [start_transformation](https://github.com/materials-marketplace/python-sdk/blob/main/marketplace/app/v0_0_1/transformation_app.py#L40). But in the new version, this is currently not possible [(here)](https://github.com/materials-marketplace/python-sdk/blob/main/marketplace/app/v0/transformation.py#L63). Should we be supporting additional arguments in the new version?
> 
> @csadorf @pablo-de-andres Please let me know your thoughts

No, the API is well-defined in the [standard-app-api](https://github.com/materials-marketplace/standard-app-api) and the updateTransformation operation does not accept any arguments in addition to the state update. This is restrictive on purpose to maintain compatibility between different apps that implement this API. A user can provide additional arguments in the form of parameters when they create the transformation: https://github.com/materials-marketplace/standard-app-api/blob/7ad7e680b27df0bfd306fb450e1baf5b8a46a49a/marketplace_standard_app_api/models/transformation.py#L28-L29

2022-08-23 13:09 UTC, csadorf requested changes

2022-08-23 13:09 UTC, csadorf commented on examples/mp_api.py
> +my_mp_app = MyMarketPlaceApp(app_id="<application_client_id>", client=mp_client)
A user should not instantiate the class directly, but use the `get_app()` function which takes care of instantiating the client: https://github.com/materials-marketplace/python-sdk/blob/56d148037ae1ffbb819cd3488b16663ddaf04b98/marketplace/app/__init__.py#L33-L35

It is actually not quite clear to me what the purpose of this example is. Under which circumstances would it be advisable to use the `MarketPlaceApp` class in an inheritance setting? It would probably almost always be preferable to use composition instead.

That said, we can make the client an optional argument and thus make this scenario easily possible so that a user does not have to pass the user id or access token (or client).

2022-08-23 13:50 UTC, csadorf commented on examples/mp_api.py
> +my_mp_app = MyMarketPlaceApp(app_id="<application_client_id>", client=mp_client)
> That said, we can make the client an optional argument and thus make this scenario easily possible so that a user does not have to pass the user id or access token (or client).

I've created https://github.com/materials-marketplace/python-sdk/pull/35 to address this.

2022-08-24 11:59 UTC, csadorf commented
Is this ready for another review?

2023-01-11 16:03 UTC, pablo-de-andres approved these changes

2023-01-11 16:51 UTC, pablo-de-andres approved these changes

2023-01-11 16:52 UTC, merged